name: Build with MSVC

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  push:
    branches:
      - '4.**'
      - '5.**'
      - 'trunk'
  pull_request:

jobs:
  build:
    permissions: {}

    runs-on: windows-latest

    timeout-minutes: 60

    steps:
      - name: Set up MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          toolset: 14.38

      - name: Fetch OCaml
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Cygwin (Cygwin)
        uses: cygwin/cygwin-install-action@v3
        with:
          packages: make,bash
          install-dir: 'D:\cygwin'

      - name: Build OCaml
        shell: bash -e {0}
        run: |
          mkdir /cygdrive/d/ocaml                                                        #
          eval $(tools/msvs-promote-path)                                                #
          ./configure --host=x86_64-pc-windows --with-flexdll --prefix=/cygdrive/d/ocaml #
          make                                                                           #
          make install                                                                   #

      - name: Display configuration and set up PATH
        run: |
          D:\ocaml\bin\ocamlc -config
          echo "D:\ocaml\bin" >> ${env:GITHUB_PATH}
          echo "/* dummy */" >> dummy.c
          cl /Bv -c dummy.c
          D:\ocaml\bin\ocamlc -verbose -c dummy.c

      - name: Run the test suite
        shell: bash -e {0}
        run: |
          eval $(tools/msvs-promote-path) #
          make tests                      #
